---
- name: run puppet
  puppet:
    puppetmaster: "{{ puppetmaster }}"
    timeout: "{{ timeout|default(omit) }}"
    show_diff: "{{ show_diff|default(omit) }}"
    facts: "{{ facts|default(omit) }}"
    facter_basename: "{{ facter_basename|default(omit) }}"
